POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImN5eiIsImlkIjoiNjIwYjgyNDdiMzczNTRhYjUwYWMwNWIyIiwiaWF0IjoxNjQ0OTMxOTQ2LCJleHAiOjE2NDQ5MzU1NDZ9.xJ60bpaWtoeId4bu2RAOpm8UXe_wu9xANVyOcZDMgeA

{
  "author": "Ching Yun Zen",
  "title": "Ball Fish",
  "likes": 123,
  "url": "www.newfishfordish.com"
}